### ISSUE TITLE
Socket 551

### ISSUE THREAD

**Issue by whotheff** [felixbrucker/jse-cli-miner#1]
Error 551 socket.io registration problem

**Comment by felixbrucker** [comment]
You'll need to fill out all the config fields from the `user` object after logging into the site.

**Comment by felixbrucker** [comment]
This error means auth/registration was unsuccessful.

**Comment by felixbrucker** [comment]
Check https://github.com/felixbrucker/jse-cli-miner#configuration for more info.

**Comment by felixbrucker** [comment]
The JSECoin developers have implemented yet another "fix" to stop this miner. While i could just make it work again, this would be a cat and mouse game and i decided to continue the development of this miner as closed source.
